// Styles:
import '@/styles/globals.css'

// Fonts:
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// Metadata:
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}