// Styles & Theme:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Global Sidebar:
import Sidebar from "@/components/mainSidebar/sidebar";

// Fonts:
import { Figtree } from "next/font/google";
import localFont from "next/font/local";
const figtreeFont = Figtree({
  variable: "--satoshiFont-font",
  subsets: ["latin"],
  weight: ["400", "800"],
  display: "swap",
  preload: true,
});
const calSans = localFont({
  src: "../fonts/CalSans-SemiBold.woff2",
  variable: "--calSans-font",
  weight: "600",
  display: "swap",
  preload: true,
});

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";
import SonnerProvider from "@/providers/sonnerProvider";

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  params: {
    tag: string;
    item: string;
  };
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-neutral-200 dark:bg-neutral-900",
          "text-slate-900 dark:text-slate-100",
          "min-h-screen antialiased",
          figtreeFont.className,
          calSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SonnerProvider>
            <Sidebar>{children}</Sidebar>
          </SonnerProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
