// Styles & Theme:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Global Sidebar:
import Sidebar from "@/components/mainSidebar/sidebar";

// Fonts:
import localFont from "next/font/local";
const satoshiFont = localFont({
  variable: "--satoshiFont-font",
  src: "../fonts/Satoshi-Variable.woff2",
  weight: "300 900",
  display: "swap",
  preload: true,
});

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-neutral-200 dark:bg-neutral-900",
          "text-slate-900 dark:text-slate-100",
          "min-h-screen antialiased",
          satoshiFont.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Sidebar>{children}</Sidebar>
        </ThemeProvider>
      </body>
    </html>
  );
}
